package net.tier1234.better_deco.datafix;

import com.google.common.collect.ImmutableMap;

import java.util.Map;

public class ModDataFixer {

    public static final Map<String, String> CHANGED_BLOCK = ImmutableMap.<String,String>builder()
            .put("better_deco:oak_cabinet", "better_deco:oak_kitchen_cabinet")
            .put("better_deco:spruce_cabinet", "better_deco:spruce_kitchen_cabinet")
            .put("better_deco:birch_cabinet", "better_deco:birch_kitchen_cabinet")
            .put("better_deco:jungle_cabinet", "better_deco:jungle_kitchen_cabinet")
            .put("better_deco:acacia_cabinet", "better_deco:acacia_kitchen_cabinet")
            .put("better_deco:dark_oak_cabinet", "better_deco:dark_oak_kitchen_cabinet")
            .put("better_deco:mangrove_cabinet", "better_deco:mangrove_kitchen_cabinet")
            .put("better_deco:cherry_cabinet", "better_deco:cherry_kitchen_cabinet")
            .put("better_deco:bamboo_cabinet", "better_deco:bamboo_kitchen_cabinet")
            .put("better_deco:crimson_cabinet", "better_deco:crimson_kitchen_cabinet")
            .put("better_deco:warped_cabinet", "better_deco:warped_kitchen_cabinet")

            .put("better_deco:oak_vertical_slab", "minecraft:oak_slab")
            .put("better_deco:spruce_vertical_slab", "minecraft:spruce_slab")
            .put("better_deco:birch_vertical_slab", "minecraft:birch_slab")
            .put("better_deco:jungle_vertical_slab", "minecraft:jungle_slab")
            .put("better_deco:acacia_vertical_slab", "minecraft:acacia_slab")
            .put("better_deco:dark_oak_vertical_slab", "minecraft:dark_oak_slab")
            .put("better_deco:mangrove_vertical_slab", "minecraft:mangrove_slab")
            .put("better_deco:cherry_vertical_slab", "minecraft:cherry_slab")
            .put("better_deco:bamboo_vertical_slab", "minecraft:bamboo_slab")
            .put("better_deco:crimson_vertical_slab", "minecraft:crimson_slab")
            .put("better_deco:warped_vertical_slab", "minecraft:warped_slab")

            .put("better_deco:big_chain", "minecraft:chain")
            .put("better_deco:chopping_board", "better_deco:oak_cutting_board")

            .put("better_deco:stripped_oak_oven", "better_deco:oak_oven")
            .put("better_deco:stripped_spruce_oven", "better_deco:spruce_oven")
            .put("better_deco:stripped_birch_oven", "better_deco:birch_oven")
            .put("better_deco:stripped_jungle_oven", "better_deco:jungle_oven")
            .put("better_deco:stripped_acacia_oven", "better_deco:acacia_oven")
            .put("better_deco:stripped_dark_oak_oven", "better_deco:dark_oak_oven")
            .put("better_deco:stripped_mangrove_oven", "better_deco:mangrove_oven")
            .put("better_deco:stripped_cherry_oven", "better_deco:cherry_oven")
            .put("better_deco:stripped_bamboo_oven", "better_deco:bamboo_oven")
            .put("better_deco:stripped_crimson_oven", "better_deco:crimson_oven")
            .put("better_deco:stripped_warped_oven", "better_deco:warped_oven")

            .put("better_deco:stripped_oak_chair", "better_deco:oak_chair")
            .put("better_deco:stripped_spruce_chair", "better_deco:spruce_chair")
            .put("better_deco:stripped_birch_chair", "better_deco:birch_chair")
            .put("better_deco:stripped_jungle_chair", "better_deco:jungle_chair")
            .put("better_deco:stripped_acacia_chair", "better_deco:acacia_chair")
            .put("better_deco:stripped_dark_oak_chair", "better_deco:dark_oak_chair")
            .put("better_deco:stripped_mangrove_chair", "better_deco:mangrove_chair")
            .put("better_deco:stripped_cherry_chair", "better_deco:cherry_chair")
            .put("better_deco:stripped_bamboo_chair", "better_deco:bamboo_chair")
            .put("better_deco:stripped_crimson_chair", "better_deco:crimson_chair")
            .put("better_deco:stripped_warped_chair", "better_deco:warped_chair")

            .put("better_deco:stripped_oak_dinning_table", "better_deco:oak_table")
            .put("better_deco:stripped_spruce_dinning_table", "better_deco:spruce_table")
            .put("better_deco:stripped_birch_dinning_table", "better_deco:birch_table")
            .put("better_deco:stripped_jungle_dinning_table", "better_deco:jungle_table")
            .put("better_deco:stripped_acacia_dinning_table", "better_deco:acacia_table")
            .put("better_deco:stripped_dark_oak_dinning_table", "better_deco:dark_oak_table")
            .put("better_deco:stripped_mangrove_dinning_table", "better_deco:mangrove_table")
            .put("better_deco:stripped_cherry_dinning_table", "better_deco:cherry_table")
            .put("better_deco:stripped_bamboo_dinning_table", "better_deco:bamboo_table")
            .put("better_deco:stripped_crimson_dinning_table", "better_deco:crimson_table")
            .put("better_deco:stripped_warped_dinning_table", "better_deco:warped_table")

            .put("better_deco:stripped_oak_kitchen_counter", "better_deco:oak_kitchen_counter")
            .put("better_deco:stripped_spruce_kitchen_counter", "better_deco:spruce_kitchen_counter")
            .put("better_deco:stripped_birch_kitchen_counter", "better_deco:birch_kitchen_counter")
            .put("better_deco:stripped_jungle_kitchen_counter", "better_deco:jungle_kitchen_counter")
            .put("better_deco:stripped_acacia_kitchen_counter", "better_deco:acacia_kitchen_counter")
            .put("better_deco:stripped_dark_oak_kitchen_counter", "better_deco:dark_oak_kitchen_counter")
            .put("better_deco:stripped_mangrove_kitchen_counter", "better_deco:mangrove_kitchen_counter")
            .put("better_deco:stripped_cherry_kitchen_counter", "better_deco:cherry_kitchen_counter")
            .put("better_deco:stripped_bamboo_kitchen_counter", "better_deco:bamboo_kitchen_counter")
            .put("better_deco:stripped_crimson_kitchen_counter", "better_deco:crimson_kitchen_counter")
            .put("better_deco:stripped_warped_kitchen_counter", "better_deco:warped_kitchen_counter")

            .put("better_deco:stripped_oak_kitchen_drawer", "better_deco:oak_kitchen_drawer")
            .put("better_deco:stripped_spruce_kitchen_drawer", "better_deco:spruce_kitchen_drawer")
            .put("better_deco:stripped_birch_kitchen_drawer", "better_deco:birch_kitchen_drawer")
            .put("better_deco:stripped_jungle_kitchen_drawer", "better_deco:jungle_kitchen_drawer")
            .put("better_deco:stripped_acacia_kitchen_drawer", "better_deco:acacia_kitchen_drawer")
            .put("better_deco:stripped_dark_oak_kitchen_drawer", "better_deco:dark_oak_kitchen_drawer")
            .put("better_deco:stripped_mangrove_kitchen_drawer", "better_deco:mangrove_kitchen_drawer")
            .put("better_deco:stripped_cherry_kitchen_drawer", "better_deco:cherry_kitchen_drawer")
            .put("better_deco:stripped_bamboo_kitchen_drawer", "better_deco:bamboo_kitchen_drawer")
            .put("better_deco:stripped_crimson_kitchen_drawer", "better_deco:crimson_kitchen_drawer")
            .put("better_deco:stripped_warped_kitchen_drawer", "better_deco:warped_kitchen_drawer")

            .put("better_deco:stripped_oak_table", "better_deco:oak_table")
            .put("better_deco:stripped_spruce_table", "better_deco:spruce_table")
            .put("better_deco:stripped_birch_table", "better_deco:birch_table")
            .put("better_deco:stripped_jungle_table", "better_deco:jungle_table")
            .put("better_deco:stripped_acacia_table", "better_deco:acacia_table")
            .put("better_deco:stripped_dark_oak_table", "better_deco:dark_oak_table")
            .put("better_deco:stripped_mangrove_table", "better_deco:mangrove_table")
            .put("better_deco:stripped_cherry_table", "better_deco:cherry_table")
            .put("better_deco:stripped_bamboo_table", "better_deco:bamboo_table")
            .put("better_deco:stripped_crimson_table", "better_deco:crimson_table")
            .put("better_deco:stripped_warped_table", "better_deco:warped_table")

            .put("better_deco:stripped_oak_coffee_table", "better_deco:oak_coffee_table")
            .put("better_deco:stripped_spruce_coffee_table", "better_deco:spruce_coffee_table")
            .put("better_deco:stripped_birch_coffee_table", "better_deco:birch_coffee_table")
            .put("better_deco:stripped_jungle_coffee_table", "better_deco:jungle_coffee_table")
            .put("better_deco:stripped_acacia_coffee_table", "better_deco:acacia_coffee_table")
            .put("better_deco:stripped_dark_oak_coffee_table", "better_deco:dark_oak_coffee_table")
            .put("better_deco:stripped_mangrove_coffee_table", "better_deco:mangrove_coffee_table")
            .put("better_deco:stripped_cherry_coffee_table", "better_deco:cherry_coffee_table")
            .put("better_deco:stripped_bamboo_coffee_table", "better_deco:bamboo_coffee_table")
            .put("better_deco:stripped_crimson_coffee_table", "better_deco:crimson_coffee_table")
            .put("better_deco:stripped_warped_coffee_table", "better_deco:warped_coffee_table")

            .put("better_deco:stripped_oak_cabinet", "better_deco:oak_kitchen_cabinet")
            .put("better_deco:stripped_spruce_cabinet", "better_deco:spruce_kitchen_cabinet")
            .put("better_deco:stripped_birch_cabinet", "better_deco:birch_kitchen_cabinet")
            .put("better_deco:stripped_jungle_cabinet", "better_deco:jungle_kitchen_cabinet")
            .put("better_deco:stripped_acacia_cabinet", "better_deco:acacia_kitchen_cabinet")
            .put("better_deco:stripped_dark_oak_cabinet", "better_deco:dark_oak_kitchen_cabinet")
            .put("better_deco:stripped_mangrove_cabinet", "better_deco:mangrove_kitchen_cabinet")
            .put("better_deco:stripped_cherry_cabinet", "better_deco:cherry_kitchen_cabinet")
            .put("better_deco:stripped_bamboo_cabinet", "better_deco:bamboo_kitchen_cabinet")
            .put("better_deco:stripped_crimson_cabinet", "better_deco:crimson_kitchen_cabinet")
            .put("better_deco:stripped_warped_cabinet", "better_deco:warped_kitchen_cabinet")

                    .put("better_deco:oak_sink_dark", "better_deco:oak_sink")
                    .put("better_deco:spruce_sink_dark", "better_deco:spruce_sink")
                    .put("better_deco:birch_sink_dark", "better_deco:birch_sink")
                    .put("better_deco:jungle_sink_dark", "better_deco:jungle_sink")
                    .put("better_deco:acacia_sink_dark", "better_deco:acacia_sink")
                    .put("better_deco:mangrove_sink_dark", "better_deco:mangrove_sink")
                    .put("better_deco:dark_oak_sink_dark", "better_deco:dark_oak_sink")
                    .put("better_deco:cherry_sink_dark", "better_deco:cherry_sink")
                    .put("better_deco:bamboo_sink_dark", "better_deco:bamboo_sink")
                    .put("better_deco:crimson_sink_dark", "better_deco:crimson_sink")
                    .put("better_deco:warped_sink_dark", "better_deco:warped_sink")

                    .put("better_deco:stone_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:stone_kitchen_drawer", "better_deco:oak_kitchen_drawer")

                    .put("better_deco:stone_cabinet", "better_deco:oak_kitchen_cabinet")
                    .put("better_deco:diorite_cabinet", "better_deco:oak_kitchen_cabinet")
                    .put("better_deco:granite_cabinet", "better_deco:oak_kitchen_cabinet")
                    .put("better_deco:deepslate_cabinet", "better_deco:oak_kitchen_cabinet")
                    .put("better_deco:deepslate_tiles_cabinet", "better_deco:oak_kitchen_cabinet")
                    .put("better_deco:blackstone_cabinet", "better_deco:oak_kitchen_cabinet")

                    .put("better_deco:spruce_diorite_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:spruce_diorite_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:spruce_diorite_oven", "better_deco:oak_oven")
                    .put("better_deco:spruce_diorite_cabinet", "better_deco:oak_kitchen_cabinet")

                    .put("better_deco:dark_oak_calcite_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:dark_oak_calcite_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:dark_oak_calcite_oven", "better_deco:oak_oven")
                    .put("better_deco:dark_oak_calcite_cabinet", "better_deco:oak_kitchen_cabinet")

                    .put("better_deco:oak_andesite_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:oak_andesite_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:oak_andesite_oven", "better_deco:oak_oven")
                    .put("better_deco:oak_andesite_cabinet", "better_deco:oak_kitchen_cabinet")

                    .put("better_deco:diorite_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:deepslate_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:granite_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:blackstone_kitchen_counter", "better_deco:oak_kitchen_counter")
                    .put("better_deco:deepslate_tiles_kitchen_counter", "better_deco:oak_kitchen_counter")

                    .put("better_deco:granite_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:diorite_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:deepslate_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:deepslate_tiles_kitchen_drawer", "better_deco:oak_kitchen_drawer")
                    .put("better_deco:blackstone_kitchen_drawer", "better_deco:oak_kitchen_drawer")

                    .put("better_deco:oak_soft_bricks", "better_deco:oak_planks")
                    .put("better_deco:spruce_soft_bricks", "better_deco:spruce_planks")
                    .put("better_deco:birch_soft_bricks", "better_deco:birch_planks")
                    .put("better_deco:dark_oak_soft_bricks", "better_deco:dark_oak_planks")
                    .put("better_deco:jungle_soft_bricks", "better_deco:jungle_planks")
                    .put("better_deco:acacia_soft_bricks", "better_deco:acacia_planks")
                    .put("better_deco:mangrove_soft_bricks", "better_deco:mangrove_planks")
                    .put("better_deco:cherry_soft_bricks", "better_deco:cherry_planks")
                    .put("better_deco:bamboo_soft_bricks", "better_deco:bamboo_planks")
                    .put("better_deco:crimson_soft_bricks", "better_deco:crimson_planks")
                    .put("better_deco:warped_soft_bricks", "better_deco:warped_planks")

                    .put("better_deco:oak_barrel", "minecraft:barrel")
                    .put("better_deco:dark_oak_barrel", "minecraft:barrel")
                    .put("better_deco:birch_barrel", "minecraft:barrel")
                    .put("better_deco:acacia_barrel", "minecraft:barrel")
                    .put("better_deco:jungle_barrel", "minecraft:barrel")
                    .put("better_deco:mangrove_barrel", "minecraft:barrel")
                    .put("better_deco:cherry_barrel", "minecraft:barrel")
                    .put("better_deco:bamboo_barrel", "minecraft:barrel")
                    .put("better_deco:crimson_barrel", "minecraft:barrel")
                    .put("better_deco:warped_barrel", "minecraft:barrel")




                    .put("better_deco:andesite_array_bricks", "minecraft:andesite")
                    .put("better_deco:andesite_mosaic_bricks", "minecraft:andesite")
                    .put("better_deco:andesite_mixed_bricks", "minecraft:andesite")
                    .put("better_deco:andesite_bricks", "minecraft:andesite")
                    .put("better_deco:raw_andesite", "minecraft:andesite")

                    .put("better_deco:diorite_array_bricks", "minecraft:diorite")
                    .put("better_deco:diorite_mosaic_bricks", "minecraft:diorite")
                    .put("better_deco:diorite_mixed_bricks", "minecraft:diorite")
                    .put("better_deco:diorite_bricks", "minecraft:diorite")
                    .put("better_deco:raw_diorite", "minecraft:diorite")

                    .put("better_deco:granite_array_bricks", "minecraft:granite")
                    .put("better_deco:granite_mosaic_bricks", "minecraft:granite")
                    .put("better_deco:granite_mixed_bricks", "minecraft:granite")
                    .put("better_deco:granite_bricks", "minecraft:granite")
                    .put("better_deco:raw_granite", "better_deco:granite")

                    .put("better_deco:oak_piled_planks", "minecraft:oak_planks")
                    .put("better_deco:oak_vertical_planks", "oak_planks")
                    .put("better_deco:oak_polished_planks", "minecraft:oak_planks")

                    .put("better_deco:birch_piled_planks", "minecraft:birch_planks")
                    .put("better_deco:birch_vertical_planks", "minecraft:birch_planks")
                    .put("better_deco:birch_polished_planks", "minecraft:birch_planks")

                    .put("better_deco:spruce_piled_planks", "minecraft:spruce_planks")
                    .put("better_deco:spruce_vertical_planks", "minecraft:spruce_planks")
                    .put("better_deco:spruce_polished_planks", "minecraft:spruce_planks")

                    .put("better_deco:jungle_piled_planks", "minecraft:jungle_planks")
                    .put("better_deco:jungle_vertical_planks", "minecraft:jungle_planks")
                    .put("better_deco:jungle_polished_planks", "minecraft:jungle_planks")

                    .put("better_deco:acacia_piled_planks", "minecraft:acacia_planks")
                    .put("better_deco:acacia_vertical_planks", "minecraft:acacia_planks")
                    .put("better_deco:acacia_polished_planks", "minecraft:acacia_planks")

                    .put("better_deco:dark_oak_piled_planks", "minecraft:dark_oak_planks")
                    .put("better_deco:dark_oak_vertical_planks", "minecraft:dark_oak_planks")
                    .put("better_deco:dark_oak_polished_planks", "minecraft:dark_oak_planks")

                    .put("better_deco:mangrove_piled_planks", "minecraft:mangrove_planks")
                    .put("better_deco:mangrove_vertical_planks", "minecraft:mangrove_planks")
                    .put("better_deco:mangrove_polished_planks", "minecraft:mangrove_planks")

                    .put("better_deco:cherry_piled_planks", "minecraft:cherry_planks")
                    .put("better_deco:cherry_vertical_planks", "minecraft:cherry_planks")
                    .put("better_deco:cherry_polished_planks", "minecraft:cherry_planks")
                    
                    .put("better_deco:bamboo_piled_planks", "minecraft:bamboo_planks")
                    .put("better_deco:bamboo_vertical_planks", "minecraft:bamboo_planks")
                    .put("better_deco:bamboo_polished_planks", "minecraft:bamboo_planks")

                    .put("better_deco:crimson_piled_planks", "minecraft:crimson_planks")
                    .put("better_deco:crimson_vertical_planks", "minecraft:crimson_planks")
                    .put("better_deco:crimson_polished_planks", "minecraft:crimson_planks")

                    .put("better_deco:warped_piled_planks", "minecraft:warped_planks")
                    .put("better_deco:warped_vertical_planks", "minecraft:warped_planks")
                    .put("better_deco:warped_polished_planks", "minecraft:warped_planks")


            .build();

}
