plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    repositories {
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "com.mrcrayfish:framework-fabric:${minecraft_version}-${framework_version}"
    modImplementation("net.tearpelato:deco_lib-fabric-1.21.1:${deco_lib_version}")
    modImplementation "curse.maven:menulogue-682371:5705587"
    modImplementation "curse.maven:configured-457570:7276575"
    modImplementation "curse.maven:catalogue-459701:6926812"

    modImplementation "curse.maven:every-compat-628539:8017076"
    modImplementation "curse.maven:selene-499980:8065894"
    modImplementation "curse.maven:terrablender-fabric-565956:6054948"
    modImplementation "curse.maven:natures-spirit-1044992:6962791"
    modImplementation "curse.maven:refurbished-furniture-897116:7473562"

    modCompileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    modCompileOnly ("net.mehvahdjukaar:everycomp-fabric:${everycomp_version}:fabric") { transitive = false }
    modCompileOnly ("net.mehvahdjukaar:moonlight-fabric:${moonlight_version}:fabric") { transitive = false }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

fabricApi {
    configureDataGeneration {
        outputDirectory.set(file("src/generated/resources"))
    }
}

loom {
    def aw = project(':fabric').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            inherit client
            name "Data Generation"
            setConfigName('Fabric Datagen')
            ideConfigGenerated(true)

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated/resources")}"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"

            runDir 'runs/datagen'
        }
    }
}
