package net.tier1234.better_deco.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.IntrinsicHolderTagsProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Item;
import net.tier1234.better_deco.registries.ModBlocks;
import net.tier1234.better_deco.registries.ModItems;
import net.tier1234.better_deco.util.ModTags;

import java.util.concurrent.CompletableFuture;

public class CommonItemTagProvider extends IntrinsicHolderTagsProvider<Item> {
    public CommonItemTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, Registries.ITEM, lookupProvider, item-> item.builtInRegistryHolder().key());
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {

        tag(ItemTags.SWORDS)
                .add(ModItems.KITCHEN_KNIFE.get().asItem());

        tag(ModTags.Items.ELECTRONIC_FURNITURES)
                .add(ModBlocks.FRIDGE_LIGHT.get().asItem())
                .add(ModBlocks.FRIDGE_DARK.get().asItem())
                .add(ModBlocks.LIGHT_MICROWAVE.get().asItem())
                .add(ModBlocks.DARK_MICROWAVE.get().asItem());
        
        tag(ModTags.Items.GENERAL)
        .add(ModBlocks.OAK_CHAIR.get().asItem())
        .add(ModBlocks.SPRUCE_CHAIR.get().asItem())
        .add(ModBlocks.BIRCH_CHAIR.get().asItem())
        .add(ModBlocks.JUNGLE_CHAIR.get().asItem())
        .add(ModBlocks.ACACIA_CHAIR.get().asItem())
        .add(ModBlocks.DARK_OAK_CHAIR.get().asItem())
        .add(ModBlocks.MANGROVE_CHAIR.get().asItem())
        .add(ModBlocks.CHERRY_CHAIR.get().asItem())
        .add(ModBlocks.BAMBOO_CHAIR.get().asItem())
        .add(ModBlocks.CRIMSON_CHAIR.get().asItem())
        .add(ModBlocks.WARPED_CHAIR.get().asItem())


        .add(ModBlocks.OAK_TABLE.get().asItem())
        .add(ModBlocks.SPRUCE_TABLE.get().asItem())
        .add(ModBlocks.BIRCH_TABLE.get().asItem())
        .add(ModBlocks.JUNGLE_TABLE.get().asItem())
        .add(ModBlocks.ACACIA_TABLE.get().asItem())
        .add(ModBlocks.DARK_OAK_TABLE.get().asItem())
        .add(ModBlocks.MANGROVE_TABLE.get().asItem())
        .add(ModBlocks.CHERRY_TABLE.get().asItem())
        .add(ModBlocks.BAMBOO_TABLE.get().asItem())
        .add(ModBlocks.CRIMSON_TABLE.get().asItem())
        .add(ModBlocks.WARPED_TABLE.get().asItem())

        .add(ModBlocks.WHITE_SOFA.get().asItem())
        .add(ModBlocks.LIGHT_GREY_SOFA.get().asItem())
        .add(ModBlocks.GREY_SOFA.get().asItem())
        .add(ModBlocks.BLACK_SOFA.get().asItem())
        .add(ModBlocks.RED_SOFA.get().asItem())
        .add(ModBlocks.ORANGE_SOFA.get().asItem())
        .add(ModBlocks.YELLOW_SOFA.get().asItem())
        .add(ModBlocks.LIME_SOFA.get().asItem())
        .add(ModBlocks.GREEN_SOFA.get().asItem())
        .add(ModBlocks.CYAN_SOFA.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_SOFA.get().asItem())
        .add(ModBlocks.BLUE_SOFA.get().asItem())
        .add(ModBlocks.PURPLE_SOFA.get().asItem())
        .add(ModBlocks.MAGENTA_SOFA.get().asItem())
        .add(ModBlocks.PINK_SOFA.get().asItem())
        .add(ModBlocks.BROWN_SOFA.get().asItem())

        .add(ModBlocks.OAK_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.SPRUCE_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.BIRCH_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.JUNGLE_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.ACACIA_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.DARK_OAK_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.MANGROVE_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.CHERRY_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.BAMBOO_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.CRIMSON_COFFEE_TABLE.get().asItem())
        .add(ModBlocks.WARPED_COFFEE_TABLE.get().asItem())

        .add(ModBlocks.WHITE_STOOL.get().asItem())
        .add(ModBlocks.LIGHT_GREY_STOOL.get().asItem())
        .add(ModBlocks.GREY_STOOL.get().asItem())
        .add(ModBlocks.BLACK_STOOL.get().asItem())
        .add(ModBlocks.BROWN_STOOL.get().asItem())
        .add(ModBlocks.RED_STOOL.get().asItem())
        .add(ModBlocks.ORANGE_STOOL.get().asItem())
        .add(ModBlocks.YELLOW_STOOL.get().asItem())
        .add(ModBlocks.LIME_STOOL.get().asItem())
        .add(ModBlocks.GREEN_STOOL.get().asItem())
        .add(ModBlocks.CYAN_STOOL.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_STOOL.get().asItem())
        .add(ModBlocks.BLUE_STOOL.get().asItem())
        .add(ModBlocks.PURPLE_STOOL.get().asItem())
        .add(ModBlocks.MAGENTA_STOOL.get().asItem())
        .add(ModBlocks.PINK_STOOL.get().asItem());
        
        tag(ModTags.Items.KITCHEN)
        .add(ModBlocks.OAK_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.SPRUCE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.BIRCH_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.JUNGLE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.ACACIA_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.DARK_OAK_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.MANGROVE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.CHERRY_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.BAMBOO_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.CRIMSON_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.WARPED_KITCHEN_COUNTER.get().asItem())

        .add(ModBlocks.OAK_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.SPRUCE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.BIRCH_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.JUNGLE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.ACACIA_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.DARK_OAK_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.MANGROVE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.CHERRY_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.BAMBOO_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.CRIMSON_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.WARPED_KITCHEN_DRAWER.get().asItem())

        .add(ModBlocks.OAK_OVEN.get().asItem())
        .add(ModBlocks.SPRUCE_OVEN.get().asItem())
        .add(ModBlocks.BIRCH_OVEN.get().asItem())
        .add(ModBlocks.JUNGLE_OVEN.get().asItem())
        .add(ModBlocks.ACACIA_OVEN.get().asItem())
        .add(ModBlocks.DARK_OAK_OVEN.get().asItem())
        .add(ModBlocks.MANGROVE_OVEN.get().asItem())
        .add(ModBlocks.CHERRY_OVEN.get().asItem())
        .add(ModBlocks.BAMBOO_OVEN.get().asItem())
        .add(ModBlocks.CRIMSON_OVEN.get().asItem())
        .add(ModBlocks.WARPED_OVEN.get().asItem())

        .add(ModBlocks.OAK_SINK.get().asItem())
        .add(ModBlocks.SPRUCE_SINK.get().asItem())
        .add(ModBlocks.BIRCH_SINK.get().asItem())
        .add(ModBlocks.JUNGLE_SINK.get().asItem())
        .add(ModBlocks.ACACIA_SINK.get().asItem())
        .add(ModBlocks.DARK_OAK_SINK.get().asItem())
        .add(ModBlocks.MANGROVE_SINK.get().asItem())
        .add(ModBlocks.CHERRY_SINK.get().asItem())
        .add(ModBlocks.BAMBOO_SINK.get().asItem())
        .add(ModBlocks.CRIMSON_SINK.get().asItem())
        .add(ModBlocks.WARPED_SINK.get().asItem())

        .add(ModBlocks.OAK_CABINET.get().asItem())
        .add(ModBlocks.SPRUCE_CABINET.get().asItem())
        .add(ModBlocks.BIRCH_CABINET.get().asItem())
        .add(ModBlocks.JUNGLE_CABINET.get().asItem())
        .add(ModBlocks.ACACIA_CABINET.get().asItem())
        .add(ModBlocks.DARK_OAK_CABINET.get().asItem())
        .add(ModBlocks.MANGROVE_CABINET.get().asItem())
        .add(ModBlocks.CHERRY_CABINET.get().asItem())
        .add(ModBlocks.BAMBOO_CABINET.get().asItem())
        .add(ModBlocks.CRIMSON_CABINET.get().asItem())
        .add(ModBlocks.WARPED_CABINET.get().asItem())

        .add(ModBlocks.WHITE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.GRAY_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.BLACK_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.BROWN_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.RED_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.ORANGE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.YELLOW_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.LIME_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.GREEN_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.CYAN_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.BLUE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.PURPLE_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.MAGENTA_KITCHEN_COUNTER.get().asItem())
        .add(ModBlocks.PINK_KITCHEN_COUNTER.get().asItem())



        .add(ModBlocks.WHITE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.GRAY_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.BLACK_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.BROWN_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.RED_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.ORANGE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.YELLOW_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.LIME_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.GREEN_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.CYAN_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.BLUE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.PURPLE_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.MAGENTA_KITCHEN_DRAWER.get().asItem())
        .add(ModBlocks.PINK_KITCHEN_DRAWER.get().asItem())

        .add(ModBlocks.WHITE_OVEN.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_OVEN.get().asItem())
        .add(ModBlocks.GRAY_OVEN.get().asItem())
        .add(ModBlocks.BLACK_OVEN.get().asItem())
        .add(ModBlocks.BROWN_OVEN.get().asItem())
        .add(ModBlocks.RED_OVEN.get().asItem())
        .add(ModBlocks.ORANGE_OVEN.get().asItem())
        .add(ModBlocks.YELLOW_OVEN.get().asItem())
        .add(ModBlocks.LIME_OVEN.get().asItem())
        .add(ModBlocks.GREEN_OVEN.get().asItem())
        .add(ModBlocks.CYAN_OVEN.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_OVEN.get().asItem())
        .add(ModBlocks.BLUE_OVEN.get().asItem())
        .add(ModBlocks.PURPLE_OVEN.get().asItem())
        .add(ModBlocks.MAGENTA_OVEN.get().asItem())
        .add(ModBlocks.PINK_OVEN.get().asItem())


        .add(ModBlocks.WHITE_SINK.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_SINK.get().asItem())
        .add(ModBlocks.GRAY_SINK.get().asItem())
        .add(ModBlocks.BLACK_SINK.get().asItem())
        .add(ModBlocks.BROWN_SINK.get().asItem())
        .add(ModBlocks.RED_SINK.get().asItem())
        .add(ModBlocks.ORANGE_SINK.get().asItem())
        .add(ModBlocks.YELLOW_SINK.get().asItem())
        .add(ModBlocks.LIME_SINK.get().asItem())
        .add(ModBlocks.GREEN_SINK.get().asItem())
        .add(ModBlocks.CYAN_SINK.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_SINK.get().asItem())
        .add(ModBlocks.BLUE_SINK.get().asItem())
        .add(ModBlocks.PURPLE_SINK.get().asItem())
        .add(ModBlocks.MAGENTA_SINK.get().asItem())
        .add(ModBlocks.PINK_SINK.get().asItem())


        .add(ModBlocks.WHITE_CABINET.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_CABINET.get().asItem())
        .add(ModBlocks.GRAY_CABINET.get().asItem())
        .add(ModBlocks.BLACK_CABINET.get().asItem())
        .add(ModBlocks.BROWN_CABINET.get().asItem())
        .add(ModBlocks.RED_CABINET.get().asItem())
        .add(ModBlocks.ORANGE_CABINET.get().asItem())
        .add(ModBlocks.YELLOW_CABINET.get().asItem())
        .add(ModBlocks.LIME_CABINET.get().asItem())
        .add(ModBlocks.GREEN_CABINET.get().asItem())
        .add(ModBlocks.CYAN_CABINET.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_CABINET.get().asItem())
        .add(ModBlocks.BLUE_CABINET.get().asItem())
        .add(ModBlocks.PURPLE_CABINET.get().asItem())
        .add(ModBlocks.MAGENTA_CABINET.get().asItem())
        .add(ModBlocks.PINK_CABINET.get().asItem())

        .add(ModBlocks.OAK_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.SPRUCE_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.BIRCH_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.JUNGLE_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.ACACIA_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.DARK_OAK_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.MANGROVE_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.CHERRY_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.BAMBOO_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.CRIMSON_CUTTING_BOARD.get().asItem())
        .add(ModBlocks.WARPED_CUTTING_BOARD.get().asItem())

        .add(ModBlocks.OAK_JAR.get().asItem())
        .add(ModBlocks.SPRUCE_JAR.get().asItem())
        .add(ModBlocks.BIRCH_JAR.get().asItem())
        .add(ModBlocks.JUNGLE_JAR.get().asItem())
        .add(ModBlocks.ACACIA_JAR.get().asItem())
        .add(ModBlocks.DARK_OAK_JAR.get().asItem())
        .add(ModBlocks.MANGROVE_JAR.get().asItem())
        .add(ModBlocks.CHERRY_JAR.get().asItem())
        .add(ModBlocks.BAMBOO_JAR.get().asItem())
        .add(ModBlocks.CRIMSON_JAR.get().asItem())
        .add(ModBlocks.WARPED_JAR.get().asItem())

        .add(ModBlocks.FRIDGE_LIGHT.get().asItem())
        .add(ModBlocks.FRIDGE_DARK.get().asItem())

        .add(ModBlocks.LIGHT_MICROWAVE.get().asItem())
        .add(ModBlocks.DARK_MICROWAVE.get().asItem())

        .add(ModBlocks.TOASTER_DARK.get().asItem())
        .add(ModBlocks.TOASTER_LIGHT.get().asItem());
        
        tag(ModTags.Items.BEDROOM)
        .add(ModBlocks.OAK_DESK.get().asItem())
        .add(ModBlocks.SPRUCE_DESK.get().asItem())
        .add(ModBlocks.BIRCH_DESK.get().asItem())
        .add(ModBlocks.JUNGLE_DESK.get().asItem())
        .add(ModBlocks.ACACIA_DESK.get().asItem())
        .add(ModBlocks.DARK_OAK_DESK.get().asItem())
        .add(ModBlocks.MANGROVE_DESK.get().asItem())
        .add(ModBlocks.CHERRY_DESK.get().asItem())
        .add(ModBlocks.BAMBOO_DESK.get().asItem())
        .add(ModBlocks.CRIMSON_DESK.get().asItem())
        .add(ModBlocks.WARPED_DESK.get().asItem())

        .add(ModBlocks.OAK_DESK_CABINET.get().asItem())
        .add(ModBlocks.SPRUCE_DESK_CABINET.get().asItem())
        .add(ModBlocks.BIRCH_DESK_CABINET.get().asItem())
        .add(ModBlocks.JUNGLE_DESK_CABINET.get().asItem())
        .add(ModBlocks.ACACIA_DESK_CABINET.get().asItem())
        .add(ModBlocks.DARK_OAK_DESK_CABINET.get().asItem())
        .add(ModBlocks.MANGROVE_DESK_CABINET.get().asItem())
        .add(ModBlocks.CHERRY_DESK_CABINET.get().asItem())
        .add(ModBlocks.BAMBOO_DESK_CABINET.get().asItem())
        .add(ModBlocks.CRIMSON_DESK_CABINET.get().asItem())
        .add(ModBlocks.WARPED_DESK_CABINET.get().asItem())

        .add(ModBlocks.OAK_BEDSIDE.get().asItem())
        .add(ModBlocks.SPRUCE_BEDSIDE.get().asItem())
        .add(ModBlocks.BIRCH_BEDSIDE.get().asItem())
        .add(ModBlocks.JUNGLE_BEDSIDE.get().asItem())
        .add(ModBlocks.ACACIA_BEDSIDE.get().asItem())
        .add(ModBlocks.MANGROVE_BEDSIDE.get().asItem())
        .add(ModBlocks.DARK_OAK_BEDSIDE.get().asItem())
        .add(ModBlocks.CHERRY_BEDSIDE.get().asItem())
        .add(ModBlocks.BAMBOO_BEDSIDE.get().asItem())
        .add(ModBlocks.CRIMSON_BEDSIDE.get().asItem())
        .add(ModBlocks.WARPED_BEDSIDE.get().asItem())

        .add(ModBlocks.WHITE_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.GRAY_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.BLACK_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.RED_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.ORANGE_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.YELLOW_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.LIME_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.GREEN_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.CYAN_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.BLUE_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.PURPLE_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.MAGENTA_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.PINK_DIGITAL_CLOCK.get().asItem())
        .add(ModBlocks.BROWN_DIGITAL_CLOCK.get().asItem());
        
        tag(ModTags.Items.OFFICE)
        .add(ModBlocks.OAK_DESK.get().asItem())
        .add(ModBlocks.SPRUCE_DESK.get().asItem())
        .add(ModBlocks.BIRCH_DESK.get().asItem())
        .add(ModBlocks.JUNGLE_DESK.get().asItem())
        .add(ModBlocks.ACACIA_DESK.get().asItem())
        .add(ModBlocks.DARK_OAK_DESK.get().asItem())
        .add(ModBlocks.MANGROVE_DESK.get().asItem())
        .add(ModBlocks.CHERRY_DESK.get().asItem())
        .add(ModBlocks.BAMBOO_DESK.get().asItem())
        .add(ModBlocks.CRIMSON_DESK.get().asItem())
        .add(ModBlocks.WARPED_DESK.get().asItem())

        .add(ModBlocks.OAK_DESK_CABINET.get().asItem())
        .add(ModBlocks.SPRUCE_DESK_CABINET.get().asItem())
        .add(ModBlocks.BIRCH_DESK_CABINET.get().asItem())
        .add(ModBlocks.JUNGLE_DESK_CABINET.get().asItem())
        .add(ModBlocks.ACACIA_DESK_CABINET.get().asItem())
        .add(ModBlocks.DARK_OAK_DESK_CABINET.get().asItem())
        .add(ModBlocks.MANGROVE_DESK_CABINET.get().asItem())
        .add(ModBlocks.CHERRY_DESK_CABINET.get().asItem())
        .add(ModBlocks.BAMBOO_DESK_CABINET.get().asItem())
        .add(ModBlocks.CRIMSON_DESK_CABINET.get().asItem())
        .add(ModBlocks.WARPED_DESK_CABINET.get().asItem())

        .add(ModBlocks.WHITE_LAMP.get().asItem())
        .add(ModBlocks.LIGHT_GRAY_LAMP.get().asItem())
        .add(ModBlocks.GRAY_LAMP.get().asItem())
        .add(ModBlocks.BLACK_LAMP.get().asItem())
        .add(ModBlocks.RED_LAMP.get().asItem())
        .add(ModBlocks.ORANGE_LAMP.get().asItem())
        .add(ModBlocks.YELLOW_LAMP.get().asItem())
        .add(ModBlocks.LIME_LAMP.get().asItem())
        .add(ModBlocks.GREEN_LAMP.get().asItem())
        .add(ModBlocks.CYAN_LAMP.get().asItem())
        .add(ModBlocks.LIGHT_BLUE_LAMP.get().asItem())
        .add(ModBlocks.BLUE_LAMP.get().asItem())
        .add(ModBlocks.PURPLE_LAMP.get().asItem())
        .add(ModBlocks.MAGENTA_LAMP.get().asItem())
        .add(ModBlocks.PINK_LAMP.get().asItem())
        .add(ModBlocks.BROWN_LAMP.get().asItem())

        .add(ModBlocks.OAK_CLOCK.get().asItem())
        .add(ModBlocks.SPRUCE_CLOCK.get().asItem())
        .add(ModBlocks.BIRCH_CLOCK.get().asItem())
        .add(ModBlocks.JUNGLE_CLOCK.get().asItem())
        .add(ModBlocks.ACACIA_CLOCK.get().asItem())
        .add(ModBlocks.DARK_OAK_CLOCK.get().asItem())
        .add(ModBlocks.MANGROVE_CLOCK.get().asItem())
        .add(ModBlocks.CHERRY_CLOCK.get().asItem())
        .add(ModBlocks.BAMBOO_CLOCK.get().asItem())
        .add(ModBlocks.CRIMSON_CLOCK.get().asItem())
        .add(ModBlocks.WARPED_CLOCK.get().asItem());
        
        tag(ModTags.Items.BATHROOM)
        .add(ModBlocks.OAK_BASIN.get().asItem())
        .add(ModBlocks.SPRUCE_BASIN.get().asItem())
        .add(ModBlocks.BIRCH_BASIN.get().asItem())
        .add(ModBlocks.JUNGLE_BASIN.get().asItem())
        .add(ModBlocks.ACACIA_BASIN.get().asItem())
        .add(ModBlocks.DARK_OAK_BASIN.get().asItem())
        .add(ModBlocks.MANGROVE_BASIN.get().asItem())
        .add(ModBlocks.CHERRY_BASIN.get().asItem())
        .add(ModBlocks.BAMBOO_BASIN.get().asItem())
        .add(ModBlocks.CRIMSON_BASIN.get().asItem())
        .add(ModBlocks.WARPED_BASIN.get().asItem())

        .add(ModBlocks.OAK_TOILET.get().asItem())
        .add(ModBlocks.SPRUCE_TOILET.get().asItem())
        .add(ModBlocks.BIRCH_TOILET.get().asItem())
        .add(ModBlocks.JUNGLE_TOILET.get().asItem())
        .add(ModBlocks.ACACIA_TOILET.get().asItem())
        .add(ModBlocks.DARK_OAK_TOILET.get().asItem())
        .add(ModBlocks.MANGROVE_TOILET.get().asItem())
        .add(ModBlocks.CHERRY_TOILET.get().asItem())
        .add(ModBlocks.BAMBOO_TOILET.get().asItem())
        .add(ModBlocks.CRIMSON_TOILET.get().asItem())
        .add(ModBlocks.WARPED_TOILET.get().asItem())

        .add(ModBlocks.OAK_BATH.get().asItem())
        .add(ModBlocks.SPRUCE_BATH.get().asItem())
        .add(ModBlocks.BIRCH_BATH.get().asItem())
        .add(ModBlocks.JUNGLE_BATH.get().asItem())
        .add(ModBlocks.ACACIA_BATH.get().asItem())
        .add(ModBlocks.DARK_OAK_BATH.get().asItem())
        .add(ModBlocks.MANGROVE_BATH.get().asItem())
        .add(ModBlocks.CHERRY_BATH.get().asItem())
        .add(ModBlocks.BAMBOO_BATH.get().asItem())
        .add(ModBlocks.CRIMSON_BATH.get().asItem())
        .add(ModBlocks.WARPED_BATH.get().asItem());
        

    }
}
