package net.tier1234.better_deco.util;

import net.minecraft.world.level.block.Block;
import net.tier1234.better_deco.registries.ModBlocks;

public class CutoutRenderLayerBlocks {

    public static Block[] getBlocks() {
        return new Block[]{
                ModBlocks.OAK_SINK.get(),
                ModBlocks.SPRUCE_SINK.get(),
                ModBlocks.BIRCH_SINK.get(),
                ModBlocks.JUNGLE_SINK.get(),
                ModBlocks.ACACIA_SINK.get(),
                ModBlocks.DARK_OAK_SINK.get(),
                ModBlocks.MANGROVE_SINK.get(),
                ModBlocks.CHERRY_SINK.get(),
                ModBlocks.BAMBOO_SINK.get(),
                ModBlocks.CRIMSON_SINK.get(),
                ModBlocks.WARPED_SINK.get(),

                ModBlocks.OAK_GLASS_TECQUE.get(),
                ModBlocks.SPRUCE_GLASS_TECQUE.get(),
                ModBlocks.BIRCH_GLASS_TECQUE.get(),
                ModBlocks.JUNGLE_GLASS_TECQUE.get(),
                ModBlocks.ACACIA_GLASS_TECQUE.get(),
                ModBlocks.DARK_OAK_GLASS_TECQUE.get(),
                ModBlocks.MANGROVE_GLASS_TECQUE.get(),
                ModBlocks.CHERRY_GLASS_TECQUE.get(),
                ModBlocks.BAMBOO_GLASS_TECQUE.get(),
                ModBlocks.CRIMSON_GLASS_TECQUE.get(),
                ModBlocks.WARPED_GLASS_TECQUE.get(),
                ModBlocks.STONE_GLASS_TECQUE.get(),

                ModBlocks.OAK_OVEN.get(),
                ModBlocks.SPRUCE_OVEN.get(),
                ModBlocks.BIRCH_OVEN.get(),
                ModBlocks.JUNGLE_OVEN.get(),
                ModBlocks.ACACIA_OVEN.get(),
                ModBlocks.DARK_OAK_OVEN.get(),
                ModBlocks.MANGROVE_OVEN.get(),
                ModBlocks.CHERRY_OVEN.get(),
                ModBlocks.BAMBOO_OVEN.get(),
                ModBlocks.CRIMSON_OVEN.get(),
                ModBlocks.WARPED_OVEN.get(),


                ModBlocks.OAK_JAR.get(),
                ModBlocks.SPRUCE_JAR.get(),
                ModBlocks.BIRCH_JAR.get(),
                ModBlocks.JUNGLE_JAR.get(),
                ModBlocks.ACACIA_JAR.get(),
                ModBlocks.DARK_OAK_JAR.get(),
                ModBlocks.MANGROVE_JAR.get(),
                ModBlocks.CHERRY_JAR.get(),
                ModBlocks.BAMBOO_JAR.get(),
                ModBlocks.CRIMSON_JAR.get(),
                ModBlocks.WARPED_JAR.get(),
                ModBlocks.LIGHT_MICROWAVE.get(),
                ModBlocks.DARK_MICROWAVE.get(),



                ModBlocks.WHITE_OVEN.get(),
                ModBlocks.LIGHT_GRAY_OVEN.get(),
                ModBlocks.GRAY_OVEN.get(),
                ModBlocks.BLACK_OVEN.get(),
                ModBlocks.BROWN_OVEN.get(),
                ModBlocks.RED_OVEN.get(),
                ModBlocks.ORANGE_OVEN.get(),
                ModBlocks.YELLOW_OVEN.get(),
                ModBlocks.LIME_OVEN.get(),
                ModBlocks.GREEN_OVEN.get(),
                ModBlocks.CYAN_OVEN.get(),
                ModBlocks.LIGHT_BLUE_OVEN.get(),
                ModBlocks.BLUE_OVEN.get(),
                ModBlocks.PURPLE_OVEN.get(),
                ModBlocks.MAGENTA_OVEN.get(),
                ModBlocks.PINK_OVEN.get(),

                ModBlocks.WHITE_OVEN.get(),
                ModBlocks.LIGHT_GRAY_OVEN.get(),
                ModBlocks.GRAY_OVEN.get(),
                ModBlocks.BLACK_OVEN.get(),
                ModBlocks.BROWN_OVEN.get(),
                ModBlocks.RED_OVEN.get(),
                ModBlocks.ORANGE_OVEN.get(),
                ModBlocks.YELLOW_OVEN.get(),
                ModBlocks.LIME_OVEN.get(),
                ModBlocks.GREEN_OVEN.get(),
                ModBlocks.CYAN_OVEN.get(),
                ModBlocks.LIGHT_BLUE_OVEN.get(),
                ModBlocks.BLUE_OVEN.get(),
                ModBlocks.PURPLE_OVEN.get(),
                ModBlocks.MAGENTA_OVEN.get(),
                ModBlocks.PINK_OVEN.get(),



                ModBlocks.WHITE_SINK.get(),
                ModBlocks.LIGHT_GRAY_SINK.get(),
                ModBlocks.GRAY_SINK.get(),
                ModBlocks.BLACK_SINK.get(),
                ModBlocks.BROWN_SINK.get(),
                ModBlocks.RED_SINK.get(),
                ModBlocks.ORANGE_SINK.get(),
                ModBlocks.YELLOW_SINK.get(),
                ModBlocks.LIME_SINK.get(),
                ModBlocks.GREEN_SINK.get(),
                ModBlocks.CYAN_SINK.get(),
                ModBlocks.LIGHT_BLUE_SINK.get(),
                ModBlocks.BLUE_SINK.get(),
                ModBlocks.PURPLE_SINK.get(),
                ModBlocks.MAGENTA_SINK.get(),
                ModBlocks.PINK_SINK.get(),

                ModBlocks.OAK_BASIN.get(),
                ModBlocks.SPRUCE_BASIN.get(),
                ModBlocks.BIRCH_BASIN.get(),
                ModBlocks.JUNGLE_BASIN.get(),
                ModBlocks.ACACIA_BASIN.get(),
                ModBlocks.DARK_OAK_BASIN.get(),
                ModBlocks.MANGROVE_BASIN.get(),
                ModBlocks.CHERRY_BASIN.get(),
                ModBlocks.BAMBOO_BASIN.get(),
                ModBlocks.CRIMSON_BASIN.get(),
                ModBlocks.WARPED_BASIN.get(),

                ModBlocks.OAK_COFFEE_TABLE.get(),
                ModBlocks.SPRUCE_COFFEE_TABLE.get(),
                ModBlocks.BIRCH_COFFEE_TABLE.get(),
                ModBlocks.JUNGLE_COFFEE_TABLE.get(),
                ModBlocks.ACACIA_COFFEE_TABLE.get(),
                ModBlocks.DARK_OAK_COFFEE_TABLE.get(),
                ModBlocks.MANGROVE_COFFEE_TABLE.get(),
                ModBlocks.CHERRY_COFFEE_TABLE.get(),
                ModBlocks.BAMBOO_COFFEE_TABLE.get(),
                ModBlocks.CRIMSON_COFFEE_TABLE.get(),
                ModBlocks.WARPED_COFFEE_TABLE.get()

        };
    }
}
