plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}


repositories {
    repositories {
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }
    maven {
        url = "https://maven.liukrast.net/"
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    implementation "com.mrcrayfish:framework-neoforge:${minecraft_version}-${framework_version}"
    implementation("net.tearpelato:deco_lib-neoforge-1.21.1:${deco_lib_version}")
    jarJar("net.tearpelato:deco_lib-neoforge-1.21.1:${deco_lib_version}")

    implementation "curse.maven:catalogue-459701:6926815"
    implementation "curse.maven:configured-457570:7276577"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    compileOnly ("net.mehvahdjukaar:everycomp-neoforge:${everycomp_version}:neoforge") { transitive = false }
    compileOnly ("net.mehvahdjukaar:moonlight-neoforge:${moonlight_version}:neoforge") { transitive = false }

    implementation "curse.maven:every-compat-628539:8017083"
    implementation "curse.maven:selene-499980:8065893"
    implementation "curse.maven:biomes-o-plenty-220318:7251965"
    implementation "curse.maven:terrablender-neoforge-940057:6054947"
    implementation "curse.maven:glitchcore-955399:5660740"


    implementation("net.liukrast:compat_manager-1.21.1:${compat_manager_version}")
    jarJar("net.liukrast:compat_manager-1.21.1:${compat_manager_version}")

}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}
